version: '3'

services:
  backend:
    build: ./backend
    command: bash -c "chmod +x ./start.sh && ./start.sh"
    volumes:
      - type: bind
        source: ./backend
        target: /code
    ports:
      - "3130:3130"
